### ISSUE TITLE
viz_utils.AxialSliceSegmaskViz duplicates the figure when changing slices

### ISSUE THREAD

**Issue by kirbyju** [ImagingDataCommons/pyplastimatch#2]
Hi Dennis, 

Thanks for your work on this repo!  I was just running through cohort preparation notebook you created and noticed that when using viz_utils.AxialSliceSegmaskViz() at the end to view the images/segmentations there is a bug.  Each time the slider is moved it redraws another image plot instead of updating the one in the widget.

Best,
Justin

**Comment by denbonte** [comment]
Hey Justin,


Unfortunately, this behavior started a few weeks ago and has not been looked through by the Colab devs yet. I opened an issue on the (hopefully relevant) GitHub repo https://github.com/googlecolab/colabtools/issues/3623 - after the ipywidgets devs pointed out it's down to Colab and not to their library! https://github.com/jupyter-widgets/ipywidgets/issues/3766

Hopefully, this gets looked into as soon as possible - I think it wouldn't be bad to have another person mentioning/commenting under that issue 🙃 

It's really a pity because it used to work pretty decently!

**Comment by kirbyju** [comment]
Hi Dennis, I encountered a similar issue with some code I was working on.  You can see how I resolved it at the very bottom of https://github.com/kirbyju/tcia_utils/commit/e8e08fcc4d2e1f9a60cbdf27d18a9b75687f1e6c.  However, I must admit that I am a rookie python developer so I'm not sure if the approach will work for what you're doing here since images + segmentation overlay is more complicated than what I was doing.

**Comment by denbonte** [comment]
Thank you, Justin! I will definitely take a look into this in the next few days 🙃

**Comment by kirbyju** [comment]
Hi again.  We had a summer student put something very similar together recently.  Check out the last 3 functions in https://github.com/kirbyju/tcia_utils/blob/main/src/tcia_utils/nbia.py#L1533.

**Comment by denbonte** [comment]
Hey @kirbyju,

Many thanks for your last comment - which I totally forgot to reply to!

I spent some time working on PyPlastimatch yesterday and today (Plastimatch, unfortunately, does not provide binaries for Ubuntu 22.04 LTS - so I compiled it from scratch, added the pre-compiled binary as a release, and a couple of functions to install Plastimatch on Ubuntu 22.04 LTS).

I also looked into this issue and fixed it as you suggested https://github.com/AIM-Harvard/pyplastimatch/commit/051febed7eae5a6988923b3aba294e4b972b13d2. This was really an easy fix, so I am a bit ashamed it took me months to implement it, but - oh well. I don't understand what's the trigger that made `plt.show()` become crucial, but I'm happy I have my dumb widgets back 😎 

I'm closing this for now. Thanks again for the help!
